# 使用的 actions:
# https://github.com/marketplace/actions/automatic-releases
name: Main

on:
  push:
    branches: [ main ]
  # schedule:
  #   - cron: '0 8 * * 0'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: download
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg curl rar python3 atomicparsley aria2 wget unzip -y
          sudo wget -O xray.zip https://github.com/XTLS/Xray-core/releases/download/v24.9.19/Xray-linux-64.zip
          sudo unzip -o ./xray.zip
          sudo chmod +x ./xray
          sudo wget -O config.json https://gist.githubusercontent.com/efrancis74/a07162d05beba30ce061ed898a3e3642/raw/config.json
          sudo sleep 5
          sudo nohup ./xray -c ./config.json >/dev/null 2>&1 &	
          sudo sleep 10
          sudo curl -sS http://ip-api.com/json --preproxy socks5://127.0.0.1:10808
          sudo sleep 5
          sudo curl -LJO https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
          sudo chmod +x ./yt-dlp
          ./yt-dlp --config-location dl.conf
          # python3 ./deal_download_files.py


      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.run_id }}
          prerelease: false
          title: ${{ github.run_id }}
          files: |
            result/*
        
